// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/cestus.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cestus_Get_FullMethodName    = "/cestus.Cestus/Get"
	Cestus_Set_FullMethodName    = "/cestus.Cestus/Set"
	Cestus_Delete_FullMethodName = "/cestus.Cestus/Delete"
)

// CestusClient is the client API for Cestus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CestusClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Set(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Result, error)
	Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error)
}

type cestusClient struct {
	cc grpc.ClientConnInterface
}

func NewCestusClient(cc grpc.ClientConnInterface) CestusClient {
	return &cestusClient{cc}
}

func (c *cestusClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Cestus_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cestusClient) Set(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Cestus_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cestusClient) Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Cestus_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CestusServer is the server API for Cestus service.
// All implementations must embed UnimplementedCestusServer
// for forward compatibility.
type CestusServer interface {
	Get(context.Context, *Request) (*Response, error)
	Set(context.Context, *Data) (*Result, error)
	Delete(context.Context, *Request) (*Result, error)
	mustEmbedUnimplementedCestusServer()
}

// UnimplementedCestusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCestusServer struct{}

func (UnimplementedCestusServer) Get(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCestusServer) Set(context.Context, *Data) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedCestusServer) Delete(context.Context, *Request) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCestusServer) mustEmbedUnimplementedCestusServer() {}
func (UnimplementedCestusServer) testEmbeddedByValue()                {}

// UnsafeCestusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CestusServer will
// result in compilation errors.
type UnsafeCestusServer interface {
	mustEmbedUnimplementedCestusServer()
}

func RegisterCestusServer(s grpc.ServiceRegistrar, srv CestusServer) {
	// If the following call pancis, it indicates UnimplementedCestusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cestus_ServiceDesc, srv)
}

func _Cestus_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CestusServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cestus_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CestusServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cestus_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CestusServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cestus_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CestusServer).Set(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cestus_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CestusServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cestus_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CestusServer).Delete(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Cestus_ServiceDesc is the grpc.ServiceDesc for Cestus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cestus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cestus.Cestus",
	HandlerType: (*CestusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Cestus_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _Cestus_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Cestus_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cestus.proto",
}
